CREATE DATABASE DBMS_PROJECT;
USE DBMS_PROJECT;

DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID VARCHAR(20) NOT NULL PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(30) NOT NULL,
CONTACT INT(15) NOT NULL ,
ADDRESS VARCHAR(50) NOT NULL,
ROLE VARCHAR(30) NOT NULL);

DROP TABLE IF EXISTS FRANCHISE;

CREATE TABLE FRANCHISE
(FRANCHISE_ID VARCHAR(20) NOT NULL PRIMARY KEY, 
FRANCHISE_LOCATION VARCHAR(30) NOT NULL, 
FRANCHISE_CONTACT INT(15) NOT NULL, 
REGISTRATION_NO INT(20) NOT NULL);

DROP TABLE IF EXISTS FRANCHISE_MANAGER;

CREATE TABLE FRANCHISE_MANAGER
(FRANCHISE_MANAGER_ID VARCHAR(20) PRIMARY KEY NOT NULL,
FRANCHISE_ID VARCHAR(20) NOT NULL,
ANALYST_ID VARCHAR(20) NOT NULL,
EMPLOYEE_ID VARCHAR(20) NOT NULL,
FOREIGN KEY (FRANCHISE_ID) REFERENCES FRANCHISE(FRANCHISE_ID),
FOREIGN KEY (ANALYST_ID) REFERENCES ANALYST(ANALYST_ID), 
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)); 

DROP TABLE IF EXISTS FRANCHISE_STAFF;

CREATE TABLE FRANCHISE_STAFF
(FRANCHISE_STAFF_ID VARCHAR(20) PRIMARY KEY NOT NULL,
FRANCHISE_ID VARCHAR(20) NOT NULL,
EMPLOYEE_ID VARCHAR(20) NOT NULL,
FOREIGN KEY (FRANCHISE_ID) REFERENCES FRANCHISE(FRANCHISE_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID));

DROP TABLE IF EXISTS ANALYST;

CREATE TABLE ANALYST
(ANALYST_ID VARCHAR(20) PRIMARY KEY NOT NULL,
EMPLOYEE_ID VARCHAR(20) NOT NULL,
REPORT_ID VARCHAR(20) NOT NULL,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
FOREIGN KEY (REPORT_ID) REFERENCES REPORT(REPORT_ID));

DROP TABLE IF EXISTS REPORT;

CREATE TABLE REPORT
(REPORT_ID VARCHAR(20) PRIMARY KEY NOT NULL,
TRACKING_DETAIL_ID VARCHAR(20) NOT NULL,
AMT_RECEIVED FLOAT(15) NOT NULL,
FOREIGN KEY (TRACKING_DETAIL_ID) REFERENCES TRACKING_DETAILS(TRACKING_DETAIL_ID));

DROP TABLE IF EXISTS TRACKING_DETAILS;

CREATE TABLE TRACKING_DETAILS
(TRACKING_DETAIL_ID VARCHAR(20) PRIMARY KEY NOT NULL,
DATE_OF_TRANSACTION date NOT NULL,
PACKAGE_ID VARCHAR(20) NOT NULL,
EST_DELIVERY_DATE date NOT NULL,
DELIVERY_STATUS VARCHAR(20) NOT NULL,
ACTUAL_DELIVERY_DATE date,
DISPATCH_DATE date,  
FOREIGN KEY(PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID));

DROP TABLE IF EXISTS TRACKING_ASSIGNMENT;

CREATE TABLE TRACKING_ASSIGNMENT
(TRACKING_DETAIL_ID VARCHAR(20) NOT NULL,
SUBROUTE_ID VARCHAR(20),
ROUTE_ID VARCHAR(20) NOT NULL,
FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ROUTE_ID),
FOREIGN KEY (SUBROUTE_ID) REFERENCES SUBROUTE(SUBROUTE_ID),
FOREIGN KEY (TRACKING_DETAIL_ID) REFERENCES TRACKING_DETAILS(TRACKING_DETAIL_ID),
PRIMARY KEY (TRACKING_DETAIL_ID, SUBROUTE_ID, ROUTE_ID));

DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE
(ROUTE_ID VARCHAR(20) PRIMARY KEY NOT NULL,
STAFF_ID VARCHAR(20) NOT NULL,
SOURCE_ID VARCHAR(20) NOT NULL,
DESTINATION_ID VARCHAR(20) NOT NULL,
FOREIGN KEY(STAFF_ID) REFERENCES FRANCHISE_STAFF(FRANCHISE_STAFF_ID),
FOREIGN KEY(SOURCE_ID) REFERENCES FRANCHISE(FRANCHISE_ID),
FOREIGN KEY(DESTINATION_ID) REFERENCES FRANCHISE(FRANCHISE_ID));

DROP TABLE IF EXISTS SUBROUTE;

CREATE TABLE SUBROUTE 
(SUBROUTE_ID VARCHAR(20) PRIMARY KEY NOT NULL,
ROUTE_ID VARCHAR(20) NOT NULL,
VEHICLE_ID VARCHAR(20) NOT NULL,
SUBROUTE_SOURCE_ID VARCHAR(20),
SUBROUTE_DESTINATION_ID VARCHAR(20),
FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ROUTE_ID),
FOREIGN KEY(SUBROUTE_SOURCE_ID) REFERENCES FRANCHISE(FRANCHISE_ID),
FOREIGN KEY(SUBROUTE_DESTINATION_ID) REFERENCES FRANCHISE(FRANCHISE_ID));

DROP TABLE IF EXISTS PACKAGE;

CREATE TABLE PACKAGE
(PACKAGE_ID VARCHAR(20) PRIMARY KEY NOT NULL,
SENDER_ID VARCHAR(20) NOT NULL,
RECEIVER_ID VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(30) NOT NULL,
DELIVERY_TYPE VARCHAR(20) NOT NULL,
PACKAGE_TYPE VARCHAR(30) NOT NULL,
WEIGHT FLOAT(15),
SOURCE_NAME VARCHAR(20) NOT NULL,
DESTINATION_NAME VARCHAR(20) NOT NULL,
SOURCE_ID VARCHAR(20),
DESTINATION_ID VARCHAR(20),
AMT_PAYABLE FLOAT(15) NOT NULL,
FOREIGN KEY (SOURCE_ID) REFERENCES FRANCHISE(FRANCHISE_ID),
FOREIGN KEY (DESTINATION_ID) REFERENCES FRANCHISE(FRANCHISE_ID),
FOREIGN KEY (RECEIVER_ID) REFERENCES RECEIVER(RECEIVER_ID),
FOREIGN KEY (SENDER_ID) REFERENCES SENDER(SENDER_ID));

DROP TABLE IF EXISTS ENQUIRY_COMPLAINT;

CREATE TABLE ENQUIRY_COMPLAINT
(ENQUIRY_ID VARCHAR(20) PRIMARY KEY NOT NULL,
STAFF_ID VARCHAR(20) NOT NULL,
CUSTOMER_ID VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(30) NOT NULL,
PACKAGE_ID VARCHAR(20),
ENQUIRY_COMPLAINT_STATUS VARCHAR(30),
FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID), 
FOREIGN KEY (STAFF_ID) REFERENCES FRANCHISE_STAFF(FRANCHISE_STAFF_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

DROP TABLE IF EXISTS SENDER;

CREATE TABLE SENDER
(SENDER_ID VARCHAR(20) PRIMARY KEY NOT NULL,
CUSTOMER_ID VARCHAR(20) NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

DROP TABLE IF EXISTS RECEIVER;

CREATE TABLE RECEIVER
(RECEIVER_ID VARCHAR(20) PRIMARY KEY NOT NULL,
CUSTOMER_ID VARCHAR(20) NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER
(CUSTOMER_ID VARCHAR(20) PRIMARY KEY NOT NULL,
CUSTOMER_NAME VARCHAR(30) NOT NULL,
CONTACT INT(15) NOT NULL,
ADDRESS VARCHAR(30) NOT NULL);

alter table TRACKING_DETAILS add column CURRENT_DELIVERY_LOCATION varchar(30);

ALTER TABLE franchise modify column franchise_contact bigint(15);

ALTER TABLE customer modify column CONTACT bigint(15);

ALTER TABLE customer modify column ADDRESS VARCHAR(50);

ALTER TABLE tracking_assignment modify column SUBROUTE_ID varchar(20);

ALTER TABLE FRANCHISE_MANAGER ADD column (MANAGER_NAME VARCHAR(30) NOT NULL,
CONTACT bigint(15) NOT NULL ,
ADDRESS VARCHAR(50) NOT NULL,
SALARY bigint(10) NOT NULL);

ALTER TABLE FRANCHISE_STAFF ADD column (MANAGER_NAME VARCHAR(30) NOT NULL,
CONTACT bigint(15) NOT NULL ,
ADDRESS VARCHAR(50) NOT NULL,
SALARY bigint(10) NOT NULL);

ALTER TABLE FRANCHISE_STAFF CHANGE COLUMN MANAGER_NAME STAFF_NAME VARCHAR(30) NOT NULL;

ALTER TABLE ANALYST ADD column (ANALYST_NAME VARCHAR(30) NOT NULL,
CONTACT bigint(15) NOT NULL ,
ADDRESS VARCHAR(50) NOT NULL,
SALARY bigint(10) NOT NULL);

alter table employee drop column employee_name;

alter table employee drop column contact;

alter table employee drop column ADDRESS;

ALTER TABLE report ADD column EXPENSE INT(20);

ALTER TABLE report ADD column REVENUE INT(20);

ALTER TABLE report ADD column ANALYST_ID VARCHAR(20);

#TO DROP REPORT ID FROM ANALYST
alter table ANALYST drop foreign key analyst_ibfk_2;
alter table analyst drop column REPORT_ID;

























